[package]
name = "wrath-math"
version = "0.1.0"
authors = ["mathiasmagnusson <mathiasmagnussons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

big-floats = []

[dependencies]
